# Generated by Django 5.2.5 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=280, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_is_public",
            field=models.BooleanField(default=False, verbose_name="Публичный профиль"),
        ),
    ]
