# Generated by Django 5.2.5 on 2026-09-04 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Account mail: verification state, link tokens and the delivery ledger.

    Existing accounts stay unverified on purpose. Backfilling ``email_verified_at``
    would assert something nobody checked — including for any address that was a
    typo — and the reset flow already handles the state: a request for an
    unverified address mails a confirmation link instead, with an identical
    response, so no account is stranded and none is granted unearned trust.
    """

    dependencies = [
        ('accounts', '0007_user_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Адрес подтверждён'),
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('password_reset', 'Сброс пароля'), ('email_verification', 'Подтверждение адреса')], max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('password_reset', 'Сброс пароля'), ('email_verification', 'Подтверждение адреса'), ('password_changed', 'Пароль изменён')], max_length=32)),
                ('to_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('expired', 'Устарело')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_emails', to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='accounts.accounttoken')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='accounttoken',
            index=models.Index(fields=['purpose', 'expires_at'], name='accounts_ac_purpose_3a27d3_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttoken',
            index=models.Index(fields=['user', 'purpose', 'consumed_at'], name='accounts_ac_user_id_20035c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountemail',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ac_status_0b1158_idx'),
        ),
    ]
