# Generated by Django 5.2.5 on 2026-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_verified_at_accounttoken_accountemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_add_to_watching',
            field=models.BooleanField(default=False, verbose_name='Автоматически добавлять в «Смотрю»'),
        ),
    ]
