from django.urls import path

from .views import (
    CharacterDetailView,
    CharacterListView,
    CreatorDetailView,
    FranchiseDetailView,
    FranchiseListView,
    GenreListView,
    GlobalSearchView,
    MediaAssetListView,
    PlaybackView,
    PlaybackResolveView,
    ScheduleView,
    SimilarTitleListView,
    EpisodeDetailView,
    WatchNavigationView,
    SourceReportView,
    TitleDetailView,
    TitleListView,
    poster_media_view,
)

urlpatterns = [
    path("titles/", TitleListView.as_view(), name="title-list"),
    path("titles/<slug:slug>/similar/", SimilarTitleListView.as_view(), name="title-similar"),
    path("titles/<slug:slug>/watch-navigation/", WatchNavigationView.as_view(), name="watch-navigation"),
    path("titles/<slug:slug>/episodes/<int:number>/", EpisodeDetailView.as_view(), name="episode-detail"),
    path("titles/<slug:slug>/", TitleDetailView.as_view(), name="title-detail"),
    path("schedule/", ScheduleView.as_view(), name="schedule"),
    path("search/", GlobalSearchView.as_view(), name="global-search"),
    path("source-reports/", SourceReportView.as_view(), name="source-report-list"),
    path("sources/<int:source_id>/playback/", PlaybackView.as_view(), name="source-playback"),
    path("playback/<str:token>/", PlaybackResolveView.as_view(), name="source-playback-resolve"),
    path("franchises/", FranchiseListView.as_view(), name="franchise-list"),
    path("genres/", GenreListView.as_view(), name="genre-list"),
    path("franchises/<slug:slug>/", FranchiseDetailView.as_view(), name="franchise-detail"),
    path("characters/", CharacterListView.as_view(), name="character-list"),
    path("characters/<slug:slug>/", CharacterDetailView.as_view(), name="character-detail"),
    path("creators/<str:slug>/", CreatorDetailView.as_view(), name="creator-detail"),
    path("media/", MediaAssetListView.as_view(), name="media-list"),
    path("media/posters/<str:filename>", poster_media_view, name="poster-media"),
]
