from django.db import migrations, models
import django.db.models.deletion


LANGUAGES = [("ru", "Русский"), ("en", "English"), ("uk", "Українська"), ("be", "Беларуская"), ("kk", "Қазақша"), ("de", "Deutsch"), ("fr", "Français"), ("es", "Español"), ("it", "Italiano"), ("ja", "日本語"), ("ko", "한국어"), ("zh", "中文")]


class Migration(migrations.Migration):
    dependencies = [("catalog", "0007_translation_admin_labels")]
    operations = [
        migrations.CreateModel(name="Character", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200)), ("slug", models.SlugField(max_length=220, unique=True)), ("original_name", models.CharField(blank=True, max_length=200)), ("description", models.TextField(blank=True)), ("image_url", models.URLField(blank=True))], options={"ordering": ["name", "slug"], "verbose_name": "Персонаж", "verbose_name_plural": "Персонажи"}),
        migrations.CreateModel(name="CharacterTranslation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("language", models.CharField("Язык", choices=LANGUAGES, max_length=8)), ("name", models.CharField("Имя", max_length=200)), ("description", models.TextField("Описание", blank=True)), ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="catalog.character"))], options={"ordering": ["language"], "verbose_name": "Перевод персонажа", "verbose_name_plural": "Переводы персонажа", "constraints": [models.UniqueConstraint(fields=("character", "language"), name="unique_character_language")]}),
        migrations.CreateModel(name="TitleCharacter", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("protagonist", "Главный герой"), ("supporting", "Второстепенный"), ("antagonist", "Антагонист"), ("cameo", "Камео")], default="supporting", max_length=20)), ("sort_order", models.PositiveIntegerField(default=0)), ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="title_links", to="catalog.character")), ("title", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="character_links", to="catalog.title"))], options={"ordering": ["sort_order", "id"], "verbose_name": "Персонаж тайтла", "verbose_name_plural": "Персонажи тайтла", "constraints": [models.UniqueConstraint(fields=("title", "character"), name="unique_title_character")]}),
        migrations.AddField(model_name="title", name="characters", field=models.ManyToManyField(blank=True, related_name="titles", through="catalog.TitleCharacter", to="catalog.character")),
        migrations.CreateModel(name="MediaAsset", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("kind", models.CharField(choices=[("image", "Изображение"), ("trailer", "Трейлер"), ("promo", "Промо")], max_length=16)), ("url", models.URLField()), ("thumbnail_url", models.URLField(blank=True)), ("caption", models.CharField(blank=True, max_length=240)), ("credit", models.CharField(max_length=240)), ("rights_reference", models.CharField(max_length=240)), ("is_published", models.BooleanField(default=False)), ("sort_order", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("character", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="catalog.character")), ("title", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="catalog.title"))], options={"ordering": ["sort_order", "id"], "verbose_name": "Медиа", "verbose_name_plural": "Медиа", "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("character__isnull", True), ("title__isnull", False)), models.Q(("character__isnull", False), ("title__isnull", True)), _connector="OR"), name="media_exactly_one_target"), models.CheckConstraint(condition=models.Q(("is_published", False), models.Q(("rights_reference", ""), _negated=True), _connector="OR"), name="published_media_requires_rights")]}),
        migrations.CreateModel(name="MediaAssetTranslation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("language", models.CharField("Язык", choices=LANGUAGES, max_length=8)), ("caption", models.CharField("Подпись", blank=True, max_length=240)), ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="catalog.mediaasset"))], options={"ordering": ["language"], "constraints": [models.UniqueConstraint(fields=("asset", "language"), name="unique_media_language")]}),
    ]
