# Generated by Django 5.2.5 on 2026-08-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_character_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='playback_adapter',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='provider',
            name='playback_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
