# Generated by Django 5.2.5 on 2026-08-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_episode_air_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='poster_origin_url',
            field=models.URLField(blank=True),
        ),
    ]
