# Generated by Django 5.2.17 on 2026-09-02 18:28
#
# Index-only, expand-safe: no column or data changes, so the previous release
# keeps running against this schema.
#
# Plain AddIndex takes an ACCESS EXCLUSIVE lock, which is acceptable here because
# the catalog is small (100 titles in production) and the build is effectively
# instant. Revisit with AddIndexConcurrently if the catalog grows into millions
# of rows.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_private_portrait_origins'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name', 'slug'], name='catalog_title_name_slug_idx'),
        ),
    ]
