# Generated by Django 5.2.5 on 2026-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_search_trigram_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['episode', 'availability'], name='src_episode_avail_idx'),
        ),
    ]
