# Generated by Django 5.2.17 on 2026-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_source_src_episode_avail_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['title', 'season_number'], name='catalog_epi_title_i_1ffd81_idx'),
        ),
    ]
