# Generated by Django 5.2.17 on 2026-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_episode_season_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='episode',
            name='unique_title_episode_number',
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('title', 'season_number', 'number'), name='unique_title_season_episode_number'),
        ),
    ]
