# Generated by Django 5.2.5 on 2026-08-24 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotificationchannel',
            name='last_digest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramnotificationchannel',
            name='schedule_digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('review_approved', 'Рецензия одобрена'), ('review_rejected', 'Рецензия отклонена'), ('report_resolved', 'Жалоба решена'), ('report_rejected', 'Жалоба отклонена')], max_length=32)),
                ('context', models.CharField(blank=True, max_length=200)),
                ('url_path', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('skipped', 'Канал не подключён'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='push_eventn_status_544be9_idx')],
            },
        ),
    ]
