import type { Locale } from "./config";

const ru: Record<string, string> = {
  "meta.homeTitle":"AniCast — аниме-каталог, расписание и сообщество","meta.homeDescription":"Каталог аниме с описаниями, персонажами, расписанием новых серий, оценками и личной библиотекой.","meta.catalogDescription":"Каталог аниме AniCast: поиск по названию, жанрам, формату и статусу выхода.","meta.communityDescription":"Оценки и одобренные рецензии зрителей AniCast без скрытых спойлеров.","meta.mediaDescription":"Трейлеры, промо-материалы и изображения аниме с подтверждённой атрибуцией прав.",
  "meta.description":"Wiki, библиотека и просмотр аниме","common.login":"Войти","common.retry":"Повторить","common.loading":"Загрузка...","common.apiUnavailable":"Сайт временно недоступен","common.apiUnavailableText":"Сервис вернётся через несколько минут — мы уже знаем о проблеме.","common.back":"← Назад","common.next":"Вперёд →","common.save":"Сохранить","common.delete":"Удалить","common.cancel":"Отмена","common.search":"Найти","common.error":"Не удалось выполнить запрос.",
  "nav.main":"Основная навигация","nav.home":"Главная","nav.catalog":"Каталог","nav.schedule":"Расписание","nav.franchises":"Франшизы","nav.characters":"Персонажи","nav.media":"Медиа","nav.community":"Сообщество","nav.more":"Ещё","nav.profile":"Профиль","nav.notifications":"Уведомления","nav.libraryShort":"Библиотека","nav.library":"МОЯ БИБЛИОТЕКА","nav.allTitles":"Все тайтлы","nav.history":"История","nav.watching":"Смотрю","nav.planned":"Запланировано","nav.completed":"Просмотрено","nav.favorites":"Избранное","nav.notes":"Заметки","nav.recommendations":"Рекомендации","language.label":"Язык интерфейса",
  "home.eyebrow":"ТВОЯ АНИМЕ-БИБЛИОТЕКА","home.title":"Продолжи свой путь","home.subtitle":"Изучай миры, сохраняй личный контекст и возвращайся к просмотру.","home.openCatalog":"Открыть каталог","home.allCatalog":"Весь каталог →","home.empty":"Каталог пока пуст","home.catalogCount":"{count} аниме уже в каталоге",
  "catalog.eyebrow":"КОЛЛЕКЦИЯ ANICAST","catalog.title":"Каталог","catalog.subtitle":"Находи новые миры и собирай библиотеку, к которой хочется возвращаться.","catalog.searchLabel":"Поиск по каталогу","catalog.searchPlaceholder":"Поиск тайтлов, персонажей, франшиз...","catalog.format":"Формат","catalog.allFormats":"Все форматы","catalog.series":"Сериал","catalog.movie":"Фильм","catalog.special":"Спешл","catalog.status":"Статус","catalog.anyStatus":"Любой статус","catalog.apply":"Применить","catalog.reset":"Сбросить","catalog.notFound":"Ничего не найдено","catalog.empty":"Каталог пока пуст","catalog.changeFilters":"Попробуй изменить параметры или посмотреть всю коллекцию.","catalog.emptyText":"Скоро здесь появятся тайтлы AniCast.","catalog.resetFilters":"Сбросить фильтры","catalog.page":"Страница {current} из {total}","catalog.found":"Найдено: {count}","catalog.sortLabel":"Сортировка","catalog.sortDefault":"Рекомендуемое","catalog.sortPopular":"По популярности","catalog.sortRecent":"Сначала новые","catalog.sortName":"По алфавиту","catalog.genre":"Жанр","catalog.allGenres":"Все жанры","catalog.random":"Случайный тайтл","title.share":"Поделиться","title.shareCopied":"Ссылка скопирована",
  "status.ongoing":"Выходит","status.finished":"Завершено","status.planned":"Скоро","status.unknown":"Статус уточняется","type.anime":"Аниме","type.movie":"Фильм","type.ova":"OVA","type.special":"Спешл","year.unknown":"Год не указан",
  "auth.loginTitle":"С возвращением","auth.loginText":"Войдите, чтобы сохранять личное состояние между устройствами.","auth.registerTitle":"Личное пространство","auth.registerText":"Создайте аккаунт для синхронизации прогресса, истории и списков.","auth.or":"или","auth.displayName":"Как к вам обращаться","auth.password":"Пароль","auth.passwordHint":"Не менее 10 символов. Не используйте распространённый или полностью цифровой пароль.","auth.wait":"Подождите...","auth.create":"Создать аккаунт","auth.haveAccount":"Уже есть аккаунт?","auth.new":"Впервые в AniCast?","auth.telegram":"Войти через Telegram-бота","auth.telegramPending":"Подтвердите вход в боте...","auth.telegramInstruction":"Нажмите Start в @{bot}, затем вернитесь на эту страницу.","auth.openBot":"Открыть бота повторно","auth.telegramUnavailable":"Вход через Telegram пока не настроен.",
  "account.eyebrow":"ВАШ АККАУНТ","account.viewer":"Зритель AniCast","account.active":"Сессия активна. Личная библиотека синхронизируется между устройствами.","account.openLibrary":"Открыть библиотеку","account.logout":"Выйти","account.loading":"Загружаем аккаунт...","account.noSession":"Сессия не найдена","account.noSessionText":"Войдите, чтобы синхронизировать списки и прогресс.","account.home":"На главную",
  "notifications.title":"Telegram-уведомления","notifications.connected":"Подключён @{bot}","notifications.description":"Подключите отдельного бота для уведомлений о новых эпизодах.","notifications.connect":"Подключить бота","notifications.disconnect":"Отключить","notifications.pending":"Подождите...","notifications.subscriptionsTitle":"Мои подписки","notifications.subscriptionsEmpty":"Вы ещё не подписаны на тайтлы — включите уведомления со страницы тайтла.","notifications.unsubscribe":"Отписаться","notifications.notLinkedWarning":"Есть подписки, но Telegram-бот не подключён — уведомления не будут приходить.","notifications.deliveriesTitle":"Последние уведомления","notifications.deliveryEpisode":"Эпизод {number}","notifications.status.sent":"доставлено","notifications.status.failed":"не доставлено","notifications.status.pending":"ожидает","notifications.subscribe":"Уведомлять о новых эпизодах","notifications.subscribed":"Уведомления включены","notifications.guest":"Войдите, чтобы подписаться на новые эпизоды.","notifications.digestTitle":"Дайджест расписания","notifications.digestDescription":"Одно сообщение утром с эпизодами, выходящими сегодня.","notifications.digestOn":"Дайджест включён","notifications.digestOff":"Дайджест выключен",
  "library.eyebrow":"ЛИЧНОЕ ПРОСТРАНСТВО","library.title":"Моя библиотека","library.subtitle":"Собирайте тайтлы, отмечайте статус и сохраняйте любимое.","library.all":"Все","library.onHold":"Отложено","library.dropped":"Брошено","library.empty":"Здесь пока пусто","library.emptyText":"Добавляйте тайтлы из каталога и распределяйте их по статусам.","library.add":"Добавить в библиотеку","library.addText":"Добавьте тайтл, чтобы вернуться к нему позже.","library.myStatus":"Мой статус","library.favorite":"В избранное","library.favoriteActive":"В избранном","library.guest":"Войдите, чтобы сохранить тайтл и синхронизировать библиотеку.",
  "history.title":"История","history.subtitle":"Только действительно открытые эпизоды и ваши явные отметки.","history.recent":"Недавно открывали","history.all":"Вся история →","history.empty":"История пока пуста","history.emptyText":"Откройте страницу эпизода из карточки тайтла.","history.watched":"Просмотрено","history.guest":"История доступна после входа","history.guestText":"Мы сохраняем только открытые эпизоды и явные отметки.","history.failed":"Историю не удалось загрузить","history.loading":"Загружаем историю...",
  "episode.number":"Эпизод {number}","episode.untitled":"Без названия","episode.open":"Открыть эпизод","episode.sources":"Источники","episode.noSources":"Источники пока не добавлены","episode.noDescription":"Описание эпизода пока не добавлено.","episode.watched":"Эпизод просмотрен","episode.inHistory":"Эпизод добавлен в историю","episode.mark":"Отметить просмотренным","episode.unmark":"Снять отметку","episode.saving":"Сохраняем открытие...",
  "source.available":"Доступен","source.unavailable":"Недоступен","source.geo":"Недоступен в регионе","source.expired":"Срок истёк","source.error":"Ошибка провайдера","source.open":"Смотреть","source.gone":"Источник больше недоступен.","source.closePlayer":"Закрыть плеер","source.playerTitle":"{name}: видеоплеер",
  "report.open":"Сообщить о проблеме","report.sent":"Жалоба отправлена","report.guest":"Войдите, чтобы сообщить о проблеме.","report.what":"Что случилось","report.unavailable":"Источник не открывается","report.wrong":"Неверный эпизод или контент","report.geo":"Недоступно в регионе","report.quality":"Проблема качества","report.other":"Другое","report.comment":"Комментарий","report.details":"Дополнительные детали","report.sending":"Отправляем...","report.send":"Отправить",
  "notes.title":"Заметки","notes.subtitle":"Ваш личный контекст к тайтлам.","notes.personal":"Личная заметка","notes.placeholder":"Мысли, детали и контекст для себя","notes.empty":"Заметок пока нет","notes.emptyText":"Добавьте заметку на странице тайтла.","notes.loading":"Загружаем заметки...","notes.guest":"Войдите, чтобы сохранить личную заметку.",
  "schedule.eyebrow":"КАЛЕНДАРЬ РЕЛИЗОВ","schedule.title":"Расписание","schedule.subtitle":"Подтверждённые даты эпизодов без выдуманного времени выхода.","schedule.today":"Сегодня","schedule.emptyText":"Здесь появляются только эпизоды с подтверждённой датой выхода.",
  "franchise.eyebrow":"СВЯЗАННЫЕ МИРЫ","franchise.title":"Франшизы","franchise.subtitle":"Серии, фильмы и ответвления, объединённые одной историей.","franchise.descriptionMissing":"Описание франшизы пока не добавлено.","franchise.empty":"Франшизы пока не добавлены","franchise.all":"← Все франшизы","franchise.label":"ФРАНШИЗА","franchise.unlinked":"Тайтлы пока не связаны","franchise.count":"{count} тайтлов",
  "title.cover":"Обложка: {name}","title.descriptionMissing":"Описание для этого тайтла пока не добавлено.","title.yearUnknown":"Год неизвестен","title.episodesCount":"{count} эп.","title.episodesUnknown":"Эпизоды уточняются","title.episodes":"Эпизоды","title.noEpisodes":"Эпизоды пока не добавлены","title.noEpisodesText":"Мы уточняем данные для этого тайтла.","title.notFound":"Тайтл не найден","title.notFoundText":"Похоже, этот тайтл ещё не появился в каталоге или был перемещён.","title.backCatalog":"Вернуться в каталог","community.title":"Сообщество","community.subtitle":"Оценки и одобренные рецензии зрителей AniCast.","community.rating":"Ваша оценка","community.average":"Средняя оценка: {value}","community.noRating":"Оценок пока нет","community.review":"Ваша рецензия","community.reviewPlaceholder":"Минимум 20 символов","community.spoiler":"Содержит спойлеры","community.submit":"Отправить на модерацию","community.pending":"На модерации","community.approved":"Одобрена","community.rejected":"Отклонена","community.publicReviews":"Рецензии зрителей","community.noReviews":"Одобренных рецензий пока нет","community.showSpoiler":"Показать спойлер","community.signIn":"Войдите, чтобы поставить оценку и написать рецензию.","character.title":"Персонажи","character.subtitle":"Герои, антагонисты и участники историй AniCast.","character.search":"Поиск персонажей...","character.empty":"Персонажи пока не добавлены","character.titles":"Связанные тайтлы","character.descriptionMissing":"Описание персонажа пока не добавлено.","role.protagonist":"Главный герой","role.supporting":"Второстепенный","role.antagonist":"Антагонист","role.cameo":"Камео","media.title":"Медиа","media.subtitle":"Опубликованные материалы с подтверждённой атрибуцией прав.","media.all":"Все","media.image":"Изображения","media.trailer":"Трейлеры","media.promo":"Промо","media.empty":"Опубликованных материалов пока нет","media.credit":"Источник: {credit}","recommendations.title":"Рекомендации","recommendations.subtitle":"Тайтлы на основе жанров вашей библиотеки.","recommendations.empty":"Пока нечего рекомендовать","recommendations.reasonGenres":"По вашим жанрам: {genres}","recommendations.reasonFranchise":"Из вашей франшизы","recommendations.dismiss":"Не интересно","recommendations.dismissed":"Скрыто из рекомендаций: {name}","recommendations.undo":"Отменить","recommendations.dismissFailed":"Не удалось скрыть тайтл, попробуйте ещё раз.","recommendations.guest":"Войдите, чтобы получить персональные рекомендации.","recommendations.loadMore":"Показать ещё","similar.title":"Похожие тайтлы"
};

const en: Record<string, string> = {
  ...ru,
  "meta.homeTitle":"AniCast — anime catalog, schedule and community","meta.homeDescription":"Explore anime descriptions, characters, upcoming episode schedules, viewer ratings and your personal library.","meta.catalogDescription":"Browse the AniCast anime catalog by title, genre, format and release status.","meta.communityDescription":"Ratings and moderated reviews from AniCast viewers, with spoilers kept under your control.","meta.mediaDescription":"Anime trailers, promotional materials and images with verified rights attribution.",
  "meta.description":"Anime wiki, library and viewing","common.login":"Sign in","common.retry":"Try again","common.loading":"Loading...","common.apiUnavailable":"The site is temporarily unavailable","common.apiUnavailableText":"The service will be back in a few minutes — we already know about it.","common.back":"← Back","common.next":"Next →","common.save":"Save","common.delete":"Delete","common.cancel":"Cancel","common.search":"Search","common.error":"Request failed.",
  "nav.main":"Main navigation","nav.home":"Home","nav.catalog":"Catalog","nav.schedule":"Schedule","nav.franchises":"Franchises","nav.characters":"Characters","nav.media":"Media","nav.community":"Community","nav.more":"More","nav.profile":"Profile","nav.notifications":"Notifications","nav.libraryShort":"Library","nav.library":"MY LIBRARY","nav.allTitles":"All titles","nav.history":"History","nav.watching":"Watching","nav.planned":"Planned","nav.completed":"Completed","nav.favorites":"Favorites","nav.notes":"Notes","nav.recommendations":"Recommendations","language.label":"Interface language",
  "home.eyebrow":"YOUR ANIME LIBRARY","home.title":"Continue your journey","home.subtitle":"Explore worlds, keep your personal context and return to watching.","home.openCatalog":"Open catalog","home.allCatalog":"Full catalog →","home.empty":"Catalog is empty","home.catalogCount":"{count} anime already in the catalog",
  "catalog.eyebrow":"ANICAST COLLECTION","catalog.title":"Catalog","catalog.subtitle":"Find new worlds and build a library worth returning to.","catalog.searchLabel":"Search catalog","catalog.searchPlaceholder":"Search titles, characters, franchises...","catalog.format":"Format","catalog.allFormats":"All formats","catalog.series":"Series","catalog.movie":"Movie","catalog.special":"Special","catalog.status":"Status","catalog.anyStatus":"Any status","catalog.apply":"Apply","catalog.reset":"Reset","catalog.notFound":"Nothing found","catalog.empty":"Catalog is empty","catalog.changeFilters":"Change the filters or browse the full collection.","catalog.emptyText":"AniCast titles will appear here soon.","catalog.resetFilters":"Reset filters","catalog.page":"Page {current} of {total}","catalog.found":"Found: {count}","catalog.sortLabel":"Sort by","catalog.sortDefault":"Recommended","catalog.sortPopular":"Most popular","catalog.sortRecent":"Newest first","catalog.sortName":"Alphabetical","catalog.genre":"Genre","catalog.allGenres":"All genres","catalog.random":"Random title","title.share":"Share","title.shareCopied":"Link copied",
  "status.ongoing":"Airing","status.finished":"Completed","status.planned":"Coming soon","status.unknown":"Status unknown","type.anime":"Anime","type.movie":"Movie","type.ova":"OVA","type.special":"Special","year.unknown":"Year not specified",
  "auth.loginTitle":"Welcome back","auth.loginText":"Sign in to keep your personal state across devices.","auth.registerTitle":"Personal space","auth.registerText":"Create an account to sync progress, history and lists.","auth.or":"or","auth.displayName":"Display name","auth.password":"Password","auth.passwordHint":"At least 10 characters. Avoid common or entirely numeric passwords.","auth.wait":"Please wait...","auth.create":"Create account","auth.haveAccount":"Already have an account?","auth.new":"New to AniCast?","auth.telegram":"Sign in with Telegram bot","auth.telegramPending":"Confirm in the bot...","auth.telegramInstruction":"Press Start in @{bot}, then return to this page.","auth.openBot":"Open bot again","auth.telegramUnavailable":"Telegram sign-in is not configured.",
  "account.eyebrow":"YOUR ACCOUNT","account.viewer":"AniCast viewer","account.active":"Session active. Your library is synced across devices.","account.openLibrary":"Open library","account.logout":"Sign out","account.loading":"Loading account...","account.noSession":"Session not found","account.noSessionText":"Sign in to sync lists and progress.","account.home":"Home",
  "notifications.title":"Telegram notifications","notifications.connected":"Connected to @{bot}","notifications.description":"Connect a separate bot for new episode notifications.","notifications.connect":"Connect bot","notifications.disconnect":"Disconnect","notifications.pending":"Please wait...","notifications.subscriptionsTitle":"My subscriptions","notifications.subscriptionsEmpty":"You have no title subscriptions yet — enable them from a title page.","notifications.unsubscribe":"Unsubscribe","notifications.notLinkedWarning":"You have subscriptions but the Telegram bot is not connected — notifications will not arrive.","notifications.deliveriesTitle":"Recent deliveries","notifications.deliveryEpisode":"Episode {number}","notifications.status.sent":"delivered","notifications.status.failed":"not delivered","notifications.status.pending":"pending","notifications.subscribe":"Notify me about new episodes","notifications.subscribed":"Notifications enabled","notifications.guest":"Sign in to subscribe to new episodes.","notifications.digestTitle":"Schedule digest","notifications.digestDescription":"One morning message with the episodes airing today.","notifications.digestOn":"Digest on","notifications.digestOff":"Digest off",
  "library.eyebrow":"PERSONAL SPACE","library.title":"My library","library.subtitle":"Collect titles, set statuses and save favorites.","library.all":"All","library.onHold":"On hold","library.dropped":"Dropped","library.empty":"Nothing here yet","library.emptyText":"Add titles from the catalog and organize them by status.","library.add":"Add to library","library.addText":"Add this title to return to it later.","library.myStatus":"My status","library.favorite":"Add to favorites","library.favoriteActive":"In favorites","library.guest":"Sign in to save this title and sync your library.",
  "history.title":"History","history.subtitle":"Only episodes you actually opened and explicit marks.","history.recent":"Recently opened","history.all":"Full history →","history.empty":"History is empty","history.emptyText":"Open an episode page from a title.","history.watched":"Watched","history.guest":"History is available after sign-in","history.guestText":"We only save opened episodes and explicit marks.","history.failed":"Could not load history","history.loading":"Loading history...",
  "episode.number":"Episode {number}","episode.untitled":"Untitled","episode.open":"Open episode","episode.sources":"Sources","episode.noSources":"No sources added yet","episode.noDescription":"Episode description is not available.","episode.watched":"Episode watched","episode.inHistory":"Episode added to history","episode.mark":"Mark as watched","episode.unmark":"Remove mark","episode.saving":"Saving opening...",
  "source.available":"Available","source.unavailable":"Unavailable","source.geo":"Unavailable in your region","source.expired":"Expired","source.error":"Provider error","source.open":"Watch","source.gone":"Source is no longer available.","source.closePlayer":"Close player","source.playerTitle":"{name}: video player",
  "report.open":"Report a problem","report.sent":"Report sent","report.guest":"Sign in to report a problem.","report.what":"What happened","report.unavailable":"Source does not open","report.wrong":"Wrong episode or content","report.geo":"Unavailable in region","report.quality":"Quality problem","report.other":"Other","report.comment":"Comment","report.details":"Additional details","report.sending":"Sending...","report.send":"Send",
  "notes.title":"Notes","notes.subtitle":"Your personal context for titles.","notes.personal":"Personal note","notes.placeholder":"Thoughts, details and context for yourself","notes.empty":"No notes yet","notes.emptyText":"Add a note on a title page.","notes.loading":"Loading notes...","notes.guest":"Sign in to save a personal note.",
  "schedule.eyebrow":"RELEASE CALENDAR","schedule.title":"Schedule","schedule.subtitle":"Confirmed episode dates without invented release times.","schedule.today":"Today","schedule.emptyText":"Only episodes with confirmed dates appear here.",
  "franchise.eyebrow":"CONNECTED WORLDS","franchise.title":"Franchises","franchise.subtitle":"Series, movies and spin-offs connected by one story.","franchise.descriptionMissing":"Franchise description is not available.","franchise.empty":"No franchises yet","franchise.all":"← All franchises","franchise.label":"FRANCHISE","franchise.unlinked":"No titles linked yet","franchise.count":"{count} titles",
  "title.cover":"Cover: {name}","title.descriptionMissing":"No description is available for this title.","title.yearUnknown":"Year unknown","title.episodesCount":"{count} ep.","title.episodesUnknown":"Episodes unknown","title.episodes":"Episodes","title.noEpisodes":"No episodes added yet","title.noEpisodesText":"We are verifying this title's data.","title.notFound":"Title not found","title.notFoundText":"This title may not be in the catalog yet or may have moved.","title.backCatalog":"Back to catalog","community.title":"Community","community.subtitle":"Ratings and approved reviews from AniCast viewers.","community.rating":"Your rating","community.average":"Average rating: {value}","community.noRating":"No ratings yet","community.review":"Your review","community.reviewPlaceholder":"At least 20 characters","community.spoiler":"Contains spoilers","community.submit":"Submit for moderation","community.pending":"Pending moderation","community.approved":"Approved","community.rejected":"Rejected","community.publicReviews":"Viewer reviews","community.noReviews":"No approved reviews yet","community.showSpoiler":"Show spoiler","community.signIn":"Sign in to rate and write a review.","character.title":"Characters","character.subtitle":"Heroes, antagonists and participants in AniCast stories.","character.search":"Search characters...","character.empty":"No characters yet","character.titles":"Related titles","character.descriptionMissing":"Character description is not available.","role.protagonist":"Protagonist","role.supporting":"Supporting","role.antagonist":"Antagonist","role.cameo":"Cameo","media.title":"Media","media.subtitle":"Published materials with verified rights attribution.","media.all":"All","media.image":"Images","media.trailer":"Trailers","media.promo":"Promo","media.empty":"No published media yet","media.credit":"Source: {credit}","recommendations.title":"Recommendations","recommendations.subtitle":"Titles based on genres in your library.","recommendations.empty":"Nothing to recommend yet","recommendations.reasonGenres":"Based on your genres: {genres}","recommendations.reasonFranchise":"From your franchise","recommendations.dismiss":"Not interested","recommendations.dismissed":"Hidden from recommendations: {name}","recommendations.undo":"Undo","recommendations.dismissFailed":"Could not hide the title, please try again.","recommendations.guest":"Sign in to get personal recommendations.","recommendations.loadMore":"Show more","similar.title":"Similar titles"
};

Object.assign(ru, {
  "nav.collections":"Коллекции",
  "collections.eyebrow":"АВТОРСКИЕ ПОДБОРКИ","collections.title":"Мои коллекции","collections.subtitle":"Собирайте тематические подборки, настраивайте порядок и делитесь публичной ссылкой.","collections.manage":"Управление коллекцией","collections.manageText":"Измените описание, доступ и порядок тайтлов.",
  "collections.name":"Название","collections.namePlaceholder":"Например, Аниме для дождливого вечера","collections.slug":"Адрес коллекции","collections.slugPlaceholder":"rainy-evening","collections.slugHint":"Строчные латинские буквы, цифры и дефисы.","collections.description":"Описание","collections.visibility":"Сделать коллекцию публичной","collections.public":"Публичная","collections.private":"Приватная","collections.share":"Ссылка:","collections.create":"Создать коллекцию","collections.creating":"Создаём...","collections.saving":"Сохраняем...",
  "collections.loading":"Загружаем коллекции...","collections.empty":"Коллекций пока нет","collections.emptyText":"Создайте первую подборку и добавляйте тайтлы с их страниц.","collections.noDescription":"Описание пока не добавлено.","collections.itemCount":"Тайтлов: {count}","collections.titles":"Тайтлы","collections.noTitles":"В коллекции пока нет тайтлов","collections.addFromTitle":"Добавьте их на странице нужного тайтла.",
  "collections.guest":"Войдите, чтобы создавать и редактировать свои коллекции.","collections.loadError":"Не удалось загрузить коллекции.","collections.saveError":"Не удалось сохранить коллекцию.","collections.deleteError":"Не удалось удалить коллекцию.","collections.itemError":"Не удалось изменить состав коллекции.","collections.reorderError":"Не удалось изменить порядок тайтлов.","collections.deleteConfirm":"Удалить эту коллекцию? Это действие нельзя отменить.",
  "collections.moveUp":"Переместить выше","collections.moveDown":"Переместить ниже","collections.remove":"Убрать","collections.addTitle":"Добавить в коллекцию","collections.added":"Добавлено","collections.createFirst":"Создать первую коллекцию","collections.publicLabel":"ПУБЛИЧНАЯ КОЛЛЕКЦИЯ","collections.publicError":"Коллекция не найдена или недоступна.","collections.by":"Автор: {name}","collections.owner":"пользователь AniCast",
  "notFound.title":"Страница потерялась","notFound.text":"Похоже, такой страницы нет или она была перемещена.","notFound.mascotAlt":"Растерянная аниме-девочка с котёнком держит записку «Страница потерялась»","notFound.toCharacters":"Персонажи","character.notFound":"Персонаж не найден","character.notFoundText":"Такого персонажа нет в каталоге — возможно, ссылка устарела.",
});

Object.assign(ru, {
  // Расписание: дни недели, статусы выхода и время в часовом поясе зрителя.
  "schedule.weekdays":"Дни недели","schedule.today":"Сегодня","schedule.tomorrow":"Завтра","schedule.yesterday":"Вчера",
  "schedule.released":"Уже вышла","schedule.airingNow":"Сейчас","schedule.inMinutes":"Через {count} мин","schedule.inHours":"Через {count} ч","schedule.inHoursMinutes":"Через {hours} ч {minutes} мин","schedule.laterToday":"Сегодня позже","schedule.upcoming":"Ожидается","schedule.timeUnknown":"Время не подтверждено",
  "schedule.episodesCount":"Эпизодов: {count}","schedule.noEpisodes":"В этот день релизов нет","schedule.noEpisodesText":"Выберите другой день недели или откройте каталог.","schedule.timezoneNote":"Время показано в вашем часовом поясе.","schedule.emptyWeek":"На этой неделе релизов нет",
  "schedule.prevWeek":"← Предыдущая неделя","schedule.nextWeek":"Следующая неделя →","schedule.thisWeek":"Текущая неделя","schedule.weekRange":"{from} — {to}",
  // Header и меню пользователя.
  "nav.openMenu":"Открыть меню пользователя","nav.closeMenu":"Закрыть меню","nav.register":"Регистрация","nav.myAccount":"Мой аккаунт","nav.logout":"Выйти","nav.openSearch":"Открыть поиск","nav.closeSearch":"Закрыть поиск",
  // Глобальный поиск.
  "search.title":"Поиск","search.placeholder":"Аниме, персонажи, франшизы...","search.hint":"Введите не менее {count} символов","search.loading":"Ищем...","search.empty":"Ничего не найдено","search.emptyText":"Проверьте написание или откройте каталог целиком.","search.error":"Поиск временно недоступен","search.errorText":"Повторите запрос через несколько секунд.","search.titles":"Аниме","search.characters":"Персонажи","search.franchises":"Франшизы","search.allResults":"Показать все результаты",
  // Страница тайтла: действия и вкладки.
  "title.watchFirst":"Смотреть 1 эпизод","title.continueEpisode":"Продолжить: эпизод {number}","watch.title":"Смотреть","watch.prev":"Предыдущая серия","watch.next":"Следующая серия","watch.sourcesHint":"Встроенные источники откроются здесь; остальные — в новой вкладке.","title.castMain":"Основной каст","title.castAll":"Весь каст","title.addLibrary":"В библиотеку","title.inLibrary":"В библиотеке","title.favorite":"Избранное","title.favoriteActive":"В избранном","title.noEpisodesYet":"Эпизоды не добавлены","title.actionsGuest":"Войдите, чтобы сохранять прогресс.",
  "title.tabOverview":"Обзор","title.tabEpisodes":"Эпизоды","title.tabCharacters":"Персонажи и авторы","title.tabCommunity":"Сообщество","title.tabNotes":"Заметки","title.description":"Описание","title.details":"Детали","title.duration":"Длительность","title.durationValue":"~{minutes} мин","title.franchiseLabel":"Франшиза","title.originalName":"Оригинальное название","title.noCast":"Персонажи пока не добавлены","title.charactersMain":"Главные персонажи","title.authorsMain":"Главные авторы","title.peopleAll":"Все персонажи и авторы →","title.characters":"Персонажи","title.authors":"Авторы","title.noAuthors":"Сведения об авторах уточняются","title.relatedWorks":"Связанные работы","credit.director":"Режиссёр","credit.producer":"Продюсер","credit.writer":"Сценарист","credit.composer":"Композитор","credit.designer":"Дизайнер",
  // Главная страница.
  "home.continueWatching":"Продолжить просмотр","home.airingNow":"Сейчас выходит","home.airingNowText":"Тайтлы с подтверждёнными датами новых эпизодов.","home.popular":"Популярное","home.popularText":"Тайтлы, которые чаще всего добавляют в библиотеку.","home.newest":"Новинки","home.newestText":"Самые свежие тайтлы каталога.","home.showAll":"Смотреть все →","home.sectionEmpty":"Пока нет данных для этого блока","home.watchNow":"Смотреть эпизод {number}"
});

Object.assign(en, {
  "schedule.weekdays":"Weekdays","schedule.today":"Today","schedule.tomorrow":"Tomorrow","schedule.yesterday":"Yesterday",
  "schedule.released":"Released","schedule.airingNow":"Now","schedule.inMinutes":"In {count} min","schedule.inHours":"In {count} h","schedule.inHoursMinutes":"In {hours} h {minutes} min","schedule.laterToday":"Later today","schedule.upcoming":"Upcoming","schedule.timeUnknown":"Time not confirmed",
  "schedule.episodesCount":"Episodes: {count}","schedule.noEpisodes":"No releases on this day","schedule.noEpisodesText":"Pick another weekday or open the catalog.","schedule.timezoneNote":"Times are shown in your timezone.","schedule.emptyWeek":"No releases this week",
  "schedule.prevWeek":"← Previous week","schedule.nextWeek":"Next week →","schedule.thisWeek":"Current week","schedule.weekRange":"{from} — {to}",
  "nav.openMenu":"Open user menu","nav.closeMenu":"Close menu","nav.register":"Sign up","nav.myAccount":"My account","nav.logout":"Sign out","nav.openSearch":"Open search","nav.closeSearch":"Close search",
  "search.title":"Search","search.placeholder":"Anime, characters, franchises...","search.hint":"Type at least {count} characters","search.loading":"Searching...","search.empty":"Nothing found","search.emptyText":"Check the spelling or browse the full catalog.","search.error":"Search is temporarily unavailable","search.errorText":"Please retry in a few seconds.","search.titles":"Anime","search.characters":"Characters","search.franchises":"Franchises","search.allResults":"Show all results",
  "title.watchFirst":"Watch episode 1","title.continueEpisode":"Continue: episode {number}","watch.title":"Watch","watch.prev":"Previous episode","watch.next":"Next episode","watch.sourcesHint":"Embedded sources open here; other sources open in a new tab.","title.castMain":"Main cast","title.castAll":"Full cast","title.addLibrary":"Add to library","title.inLibrary":"In library","title.favorite":"Favorite","title.favoriteActive":"In favorites","title.noEpisodesYet":"No episodes added","title.actionsGuest":"Sign in to keep your progress.",
  "title.tabOverview":"Overview","title.tabEpisodes":"Episodes","title.tabCharacters":"Characters & creators","title.tabCommunity":"Community","title.tabNotes":"Notes","title.description":"Description","title.details":"Details","title.duration":"Runtime","title.durationValue":"~{minutes} min","title.franchiseLabel":"Franchise","title.originalName":"Original title","title.noCast":"No characters added yet","title.charactersMain":"Main characters","title.authorsMain":"Main creators","title.peopleAll":"All characters and creators →","title.characters":"Characters","title.authors":"Creators","title.noAuthors":"Creator details are being verified","title.relatedWorks":"Related works","credit.director":"Director","credit.producer":"Producer","credit.writer":"Writer","credit.composer":"Composer","credit.designer":"Designer",
  "home.continueWatching":"Continue watching","home.airingNow":"Airing now","home.airingNowText":"Titles with confirmed upcoming episode dates.","home.popular":"Popular","home.popularText":"Titles most often added to libraries.","home.newest":"Newest","home.newestText":"The freshest titles in the catalog.","home.showAll":"See all →","home.sectionEmpty":"No data for this block yet","home.watchNow":"Watch episode {number}"
});

Object.assign(en, {
  "nav.collections":"Collections",
  "collections.eyebrow":"CURATED LISTS","collections.title":"My collections","collections.subtitle":"Build themed lists, arrange titles and share a public link.","collections.manage":"Manage collection","collections.manageText":"Edit its description, visibility and title order.",
  "collections.name":"Name","collections.namePlaceholder":"For example, Anime for a rainy evening","collections.slug":"Collection URL","collections.slugPlaceholder":"rainy-evening","collections.slugHint":"Lowercase Latin letters, numbers and hyphens.","collections.description":"Description","collections.visibility":"Make this collection public","collections.public":"Public","collections.private":"Private","collections.share":"Share link:","collections.create":"Create collection","collections.creating":"Creating...","collections.saving":"Saving...",
  "collections.loading":"Loading collections...","collections.empty":"No collections yet","collections.emptyText":"Create your first list and add titles from their pages.","collections.noDescription":"No description yet.","collections.itemCount":"Titles: {count}","collections.titles":"Titles","collections.noTitles":"This collection has no titles yet","collections.addFromTitle":"Add them from a title page.",
  "collections.guest":"Sign in to create and manage your collections.","collections.loadError":"Could not load collections.","collections.saveError":"Could not save the collection.","collections.deleteError":"Could not delete the collection.","collections.itemError":"Could not update the collection titles.","collections.reorderError":"Could not reorder the titles.","collections.deleteConfirm":"Delete this collection? This action cannot be undone.",
  "collections.moveUp":"Move up","collections.moveDown":"Move down","collections.remove":"Remove","collections.addTitle":"Add to collection","collections.added":"Added","collections.createFirst":"Create your first collection","collections.publicLabel":"PUBLIC COLLECTION","collections.publicError":"Collection not found or unavailable.","collections.by":"By {name}","collections.owner":"AniCast user",
  "notFound.title":"Page got lost","notFound.text":"This page does not exist or may have moved.","notFound.mascotAlt":"A puzzled anime girl with a kitten holding a 'Page got lost' note","notFound.toCharacters":"Characters","character.notFound":"Character not found","character.notFoundText":"This character is not in the catalog — the link may be outdated.",
});

Object.assign(ru, {
  // Личный кабинет: сводка, разделы и подсказки.
  "account.title":"Личный кабинет","account.subtitle":"Ваш профиль, статистика и быстрые переходы по личным разделам.","account.noEmail":"Email не указан",
  "account.statsLabel":"Статистика библиотеки","account.statsOnHold":"Отложено","account.statsRatings":"Оценки","account.statsReviews":"Рецензии","account.sections":"Личные разделы",
  "account.sectionLibraryHint":"{count} в списке","account.sectionHistoryHint":"{count} просмотрено","account.sectionNotesHint":"{count} заметок","account.sectionCollectionsHint":"{count} подборок","account.sectionRecommendationsHint":"На основе вашей библиотеки","account.sectionSettingsHint":"Уведомления и язык интерфейса",
  "account.recentNotes":"Последние заметки","account.collectionsHeading":"Мои коллекции","account.recommendedHeading":"Вам может понравиться",
  "home.heroEyebrow":"Продолжить просмотр","home.continueEpisode":"Продолжить {number} серию","home.aboutTitle":"О тайтле","home.heroProgress":"просмотрено {watched} из {total}",
  "profile.tabOverview":"Обзор","profile.tabLibrary":"Библиотека","profile.tabHistory":"История",
  "profile.statsHours":"Часы","profile.statsAvgRating":"Средняя оценка","profile.genreToCatalog":"Открыть в каталоге",
  "profile.favoriteGenres":"Любимые жанры","profile.genreCount":"{count} тайтлов",
  "profile.activityTitle":"Активность просмотров","profile.activitySubtitle":"Отмеченные эпизоды за последние 12 месяцев","profile.activityLabel":"График активности просмотров по месяцам","profile.activityCount":"Эпизодов: {count}",
  "profile.guest":"Гость",
  // Настройки: отдельный приватный маршрут (design freeze §17).
  "settings.title":"Настройки","settings.subtitle":"Публичный профиль, уведомления и язык интерфейса.","settings.languageHint":"Язык переключается кнопкой в шапке сайта и сохраняется в аккаунте.",
  // Представления внутри вкладки «Библиотека».
  "library.viewTitles":"Тайтлы","library.viewCollections":"Коллекции",
  // Единый сценарий просмотра: озвучка, доступные серии и плеер.
  "watch.navigation":"Выбор озвучки и серии","watch.voice":"Озвучка или субтитры","watch.noVoice":"Доступных озвучек пока нет",
  "watch.episodeCount":"{count} эп.","watch.episodeRange":"Диапазон серий","watch.available":"Доступно серий",
  "watch.episodeUnavailable":"Этой серии нет в выбранной озвучке","watch.voiceUnavailable":"Серии {number} нет в варианте «{name}». Выберите доступную серию.",
  "watch.neighborEpisodes":"Соседние доступные серии","watch.playEpisode":"Смотреть серию {number}","watch.noPlayer":"Для этой серии нет доступного плеера",
  "watch.chooseAvailableEpisode":"Выберите активную кнопку серии или другую озвучку.","watch.sourceDetails":"Все источники и диагностика",
  "watch.kind.dub":"озвучка","watch.kind.sub":"субтитры","watch.kind.raw":"оригинал",
  "watch.choiceShare":"выбор зрителей",
});

Object.assign(en, {
  "account.title":"Account","account.subtitle":"Your profile, statistics and shortcuts to personal sections.","account.noEmail":"No email provided",
  "account.statsLabel":"Library statistics","account.statsOnHold":"On hold","account.statsRatings":"Ratings","account.statsReviews":"Reviews","account.sections":"Personal sections",
  "account.sectionLibraryHint":"{count} in list","account.sectionHistoryHint":"{count} watched","account.sectionNotesHint":"{count} notes","account.sectionCollectionsHint":"{count} lists","account.sectionRecommendationsHint":"Based on your library","account.sectionSettingsHint":"Notifications and language",
  "account.recentNotes":"Recent notes","account.collectionsHeading":"My collections","account.recommendedHeading":"You may also like",
  "home.heroEyebrow":"Continue watching","home.continueEpisode":"Continue episode {number}","home.aboutTitle":"About the title","home.heroProgress":"watched {watched} of {total}",
  "profile.tabOverview":"Overview","profile.tabLibrary":"Library","profile.tabHistory":"History",
  "profile.statsHours":"Hours","profile.statsAvgRating":"Average rating","profile.genreToCatalog":"Show in catalog",
  "profile.favoriteGenres":"Favorite genres","profile.genreCount":"{count} titles",
  "profile.activityTitle":"Viewing activity","profile.activitySubtitle":"Episodes marked during the last 12 months","profile.activityLabel":"Monthly viewing activity chart","profile.activityCount":"Episodes: {count}",
  "profile.guest":"Guest",
  "settings.title":"Settings","settings.subtitle":"Public profile, notifications and interface language.","settings.languageHint":"Switch the language with the header control; the choice is stored in your account.",
  "library.viewTitles":"Titles","library.viewCollections":"Collections",
  "watch.navigation":"Voice-over and episode navigation","watch.voice":"Voice-over or subtitles","watch.noVoice":"No playable voice-overs yet",
  "watch.episodeCount":"{count} eps.","watch.episodeRange":"Episode range","watch.available":"Episodes available",
  "watch.episodeUnavailable":"This episode is not available in the selected voice-over","watch.voiceUnavailable":"Episode {number} is not available in “{name}”. Choose an available episode.",
  "watch.neighborEpisodes":"Adjacent available episodes","watch.playEpisode":"Watch episode {number}","watch.noPlayer":"No playable source for this episode",
  "watch.chooseAvailableEpisode":"Choose an active episode button or another voice-over.","watch.sourceDetails":"All sources and diagnostics",
  "watch.kind.dub":"dub","watch.kind.sub":"subtitles","watch.kind.raw":"original",
  "watch.choiceShare":"viewer choice",
});

Object.assign(ru, {
  "footer.tagline":"Каталог, расписание и личная библиотека для тех, кто любит аниме.",
  "footer.navigation":"Навигация в подвале сайта",
  "visits.label":"Статистика посещений сайта",
  "visits.total":"посещений",
  "visits.today":"сегодня",
  "social.eyebrow":"СООБЩЕСТВО ANICAST",
  "social.settingsTitle":"Публичный профиль",
  "social.settingsDescription":"Настройте имя и краткое описание. Профиль появится в сообществе только после вашего явного согласия.",
  "social.displayName":"Имя в сообществе",
  "social.bio":"О себе",
  "social.bioPlaceholder":"Например: любимые жанры, студии и истории, которые хочется обсуждать.",
  "social.publicProfile":"Показывать публичный профиль",
  "social.publicProfileHint":"Будут видны только имя, описание, одобренные рецензии и коллекции, которые вы сами сделали публичными.",
  "social.profileSaved":"Профиль сохранён",
  "social.openProfile":"Открыть профиль",
  "social.publicBadge":"ПУБЛИЧНЫЙ ПРОФИЛЬ",
  "social.collections":"Коллекции",
  "social.reviews":"Рецензии",
  "social.publicCollections":"Публичные коллекции",
  "social.publishedReviews":"Опубликованные рецензии",
  "social.noPublicCollections":"Публичных коллекций пока нет.",
  "social.noPublishedReviews":"Опубликованных рецензий пока нет.",
  "social.profileDescription":"Профиль {name} в сообществе AniCast: публичные коллекции и рецензии.",
  "social.follow":"Подписаться",
  "social.unfollow":"Отписаться",
  "social.signInToFollow":"Войти, чтобы подписаться",
  "social.editOwnProfile":"Настроить профиль",
  "social.followers":"Подписчики",
  "social.followersCount":"Подписчиков: {count}",
  "social.feedTabs":"Разделы ленты сообщества",
  "social.feedAll":"Все рецензии",
  "social.feedFollowing":"Мои подписки",
  "social.feedEmpty":"В ленте подписок пока пусто",
  "social.feedEmptyHint":"Подпишитесь на интересные публичные профили — их новые рецензии и обновления коллекций появятся здесь.",
  "social.collectionUpdated":"Коллекция обновлена",
  "social.reviewPublished":"Рецензия опубликована",
});

Object.assign(en, {
  "footer.tagline":"Anime catalog, schedule and personal library built for fans.",
  "footer.navigation":"Footer navigation",
  "visits.label":"Site visit statistics",
  "visits.total":"visits",
  "visits.today":"today",
  "social.eyebrow":"ANICAST COMMUNITY",
  "social.settingsTitle":"Public profile",
  "social.settingsDescription":"Choose your community name and short bio. Your profile appears only after you explicitly make it public.",
  "social.displayName":"Community name",
  "social.bio":"About you",
  "social.bioPlaceholder":"For example: favorite genres, studios and stories you enjoy discussing.",
  "social.publicProfile":"Show my public profile",
  "social.publicProfileHint":"Only your name, bio, approved reviews and collections you explicitly made public will be visible.",
  "social.profileSaved":"Profile saved",
  "social.openProfile":"Open profile",
  "social.publicBadge":"PUBLIC PROFILE",
  "social.collections":"Collections",
  "social.reviews":"Reviews",
  "social.publicCollections":"Public collections",
  "social.publishedReviews":"Published reviews",
  "social.noPublicCollections":"No public collections yet.",
  "social.noPublishedReviews":"No published reviews yet.",
  "social.profileDescription":"{name}'s AniCast community profile, public collections and reviews.",
  "social.follow":"Follow",
  "social.unfollow":"Unfollow",
  "social.signInToFollow":"Sign in to follow",
  "social.editOwnProfile":"Edit profile",
  "social.followers":"Followers",
  "social.followersCount":"Followers: {count}",
  "social.feedTabs":"Community feed sections",
  "social.feedAll":"All reviews",
  "social.feedFollowing":"Following",
  "social.feedEmpty":"Your following feed is empty",
  "social.feedEmptyHint":"Follow public profiles you enjoy. Their new reviews and collection updates will appear here.",
  "social.collectionUpdated":"Collection updated",
  "social.reviewPublished":"Review published",
});

export const dictionaries: Record<Locale, Record<string, string>> = { ru, en };
