# Generated by Django 5.2.5 on 2026-08-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('site', 'Сайт'), ('api', 'API каталога'), ('readiness', 'Readiness backend')], db_index=True, max_length=16)),
                ('checked_at', models.DateTimeField(db_index=True)),
                ('ok', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Проба доступности',
                'verbose_name_plural': 'Пробы доступности',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['target', 'checked_at'], name='common_avai_target_6da534_idx')],
            },
        ),
    ]
