# Generated by Django 5.2.5 on 2026-08-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("follower", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_following", to=settings.AUTH_USER_MODEL)),
                ("following", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profile_followers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["following", "created_at"], name="community_p_followi_eb6c3e_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("follower", "following"), name="unique_profile_follow"),
                    models.CheckConstraint(condition=models.Q(("follower", models.F("following")), _negated=True), name="prevent_self_profile_follow"),
                ],
            },
        ),
    ]
